version: '2'

networks:
  hospital:

services:
  redis1:
    image: 'redis:latest'
    container_name: redis.hosp1.ehrNet.com
    command: redis-server --requirepass hosp1ehrNet
    ports:
      - "6379:6379"
    networks:
      - hospital

  redis2:
    image: 'redis:latest'
    container_name: redis.hosp2.ehrNet.com
    command: redis-server --requirepass hosp2ehrNet
    ports:
      - "6380:6379"
    networks:
      - hospital

  redis3:
    image: 'redis:latest'
    container_name: redis.hosp3.ehrNet.com
    command: redis-server --requirepass hosp3ehrNet
    ports:
      - "6381:6379"
    networks:
      - hospital